name: starforce_sim
description: A simulator for equipment upgrades in an online game, with probabilities, costs, and event-based mechanics.

version: 1.0.0
environment:
  sdk: ^3.2.0
  # flutter: '>= 3.22.0'

dependencies:
  # For charting visualization, if needed later
  # charts_flutter: ^0.11.0
  # Use provider for state management (optional for UI purposes)
  # provider: ^6.0.0
    csv: ^5.0.1

dev_dependencies:
  # flutter_test:
    # sdk: ^3.5.0
  test: ^1.19.0 # Dart testing framework for unit tests
  lints: ^5.0.0 # Recommended linter rules

flutter:
  uses-material-design: true
